apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecrets
metadata:
  name: cluster
spec:
  externalSecretsConfig:
    bitwardenSecretManagerProvider:
      enabled: 'true'
      secretRef:
        name: bitwarden-tls-certs
