apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: default
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            namespace: external-secrets
            name: bitwarden-credentials
            key:
      organizationID:
      projectID:
