apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
- target:
    kind: Deployment
    name: reviews-v3
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Always
- target:
    kind: Deployment
    name: reviews-v2
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: quay.io/sail-dev/examples-bookinfo-reviews-v2:1.21.0
