apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/bootstrap/openshift-gitops/overlays/all
  - ../../apps/bootstrap/gitops-applications/overlays/workload-prod-a
