apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-cop/gitops-catalog.git/advanced-cluster-management/operator/overlays/release-2.15?ref=7727f2425149abf9e061665c6d1268a70238c138
components:
  - ../../../../catalog/components/syncwaves/operators
