apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - managedclusterset.yaml
  - namespace-policies.yaml
  - managedclustersetbinding-argocd.yaml
  - managedclustersetbinding-policies.yaml
  - placement-argocd.yaml
  - placement-policies.yaml
  - managedcluster-workload-a.yaml
  - managedcluster-workload-b.yaml
