apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: workload-a
  labels:
    type: workload
    name: workload-a
    cluster.open-cluster-management.io/clusterset: workload
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: workload-a
  namespace: workload-a
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
