apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: cluster-banner
spec:
  text: "Cluster: hub-prod-a, Type: hub, Environment: hub-prod"
  color: "#ffffff"
  backgroundColor: "#0066cc"
