apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: default
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      organizationID: 9c351068-4b85-4ec4-90d6-b37300cb91a7
      projectID: 682ed35a-9781-4a47-a8b7-b37c005d51bd
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-token
            namespace: external-secrets
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
