name: CI Dyff Check

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  dyff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.25'

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Install dyff
        run: go install github.com/homeport/dyff/cmd/dyff@v1.12.0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch target branch
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }} --depth=1

      - name: Run Dyff Recipe
        run: |
          just dyff "origin/${{ github.base_ref }}" github > dyff_report.md
          cat dyff_report.md >> $GITHUB_STEP_SUMMARY

      - name: Save PR number
        run: echo "${{ github.event.pull_request.number }}" > pr_number.txt

      - name: Upload Dyff report artifact
        uses: actions/upload-artifact@v4
        with:
          name: dyff-report
          path: |
            dyff_report.md
            pr_number.txt
          retention-days: 1
